services:
  patroni1:
    image: ghcr.io/zalando/spilo-17:4.0-p2
    container_name: patroni1
    ports: ["${PATRONI1_HOST_PORT}:5432", "8008:8008"]
    environment:
      NAME: "patroni1"
      PATRONI_NAME: "patroni1"
      SCOPE: "${CLUSTER_SCOPE}"

      PATRONI_RESTAPI_LISTEN: "0.0.0.0:8008"
      PATRONI_RESTAPI_CONNECT_ADDRESS: "patroni1:8008"

      PATRONI_POSTGRESQL_LISTEN: "0.0.0.0:5432"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni1:5432"

      PATRONI_POSTGRESQL_DATA_DIR: /home/postgres/pgdata/pgroot/data"

      # PATRONI_POSTGRESQL_PARAMETERS_MAX_WAL_SIZE: "${MAX_WAL_SIZE}"
      # PATRONI_POSTGRESQL_PARAMETERS_SHARED_BUFFERS: "${SHARED_BUFFERS}"
      # PATRONI_POSTGRESQL_PARAMETERS_MAX_CONNECTIONS: "${MAX_CONN}"

      PATRONI_SUPERUSER_USERNAME: "${SUPERUSER}"
      PATRONI_SUPERUSER_PASSWORD: "${SUPERPASS}"
      PATRONI_REPLICATION_USERNAME: "${REPLUSER}"
      PATRONI_REPLICATION_PASSWORD: "${REPLPASS}"

      PATRONI_POSTGRESQL_PARAMETERS_TIMEZONE: "${TIME_ZONE}"
      TZ: "${TIME_ZONE}"

      PATRONI_ETCD_HOSTS: "etcd:2379"
      PATRONI_DCS: |
        {"etcd3":{"hosts":["etcd:2379"]}, "loop_wait": 10, "ttl": 30, "retry_timeout": 10, "maximum_lag_on_failover": 1048576, "postgresql": {"use_pg_rewind": true}}
    volumes:
      - ./patroni_data/node1:/home/postgres/pgdata/pgroot/data
    depends_on:
      etcd:
        condition: service_healthy
    networks: [patroninet]

  patroni2:
    image: ghcr.io/zalando/spilo-17:4.0-p2
    container_name: patroni2
    ports: ["${PATRONI2_HOST_PORT}:5432", "8009:8008"]
    environment:
      NAME: "patroni2"
      PATRONI_NAME: "patroni2"
      SCOPE: "${CLUSTER_SCOPE}"

      PATRONI_RESTAPI_LISTEN: "0.0.0.0:8008"
      PATRONI_RESTAPI_CONNECT_ADDRESS: "patroni2:8008"

      PATRONI_POSTGRESQL_LISTEN: "0.0.0.0:5432"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni2:5432"

      PATRONI_POSTGRESQL_DATA_DIR: "/home/postgres/pgdata/pgroot/data"

      PATRONI_SUPERUSER_USERNAME: "${SUPERUSER}"
      PATRONI_SUPERUSER_PASSWORD: "${SUPERPASS}"
      PATRONI_REPLICATION_USERNAME: "${REPLUSER}"
      PATRONI_REPLICATION_PASSWORD: "${REPLPASS}"

      PATRONI_POSTGRESQL_PARAMETERS_TIMEZONE: "${TIME_ZONE}"
      TZ: "${TIME_ZONE}"

      PATRONI_ETCD_HOSTS: "etcd:2379"
      PATRONI_DCS: |
        {"etcd3":{"hosts":["etcd:2379"]}, "loop_wait": 10, "ttl": 30, "retry_timeout": 10, "maximum_lag_on_failover": 1048576, "postgresql": {"use_pg_rewind": true}}
    volumes:
      - ./patroni_data/node2:/home/postgres/pgdata/pgroot/data
    depends_on:
      etcd:
        condition: service_healthy
    networks: [patroninet]

  patroni3:
    image: ghcr.io/zalando/spilo-17:4.0-p2
    container_name: patroni3
    ports: ["${PATRONI3_HOST_PORT}:5432", "8010:8008"]
    environment:
      NAME: "patroni3"
      PATRONI_NAME: "patroni3"
      SCOPE: "${CLUSTER_SCOPE}"

      PATRONI_RESTAPI_LISTEN: "0.0.0.0:8008"
      PATRONI_RESTAPI_CONNECT_ADDRESS: "patroni3:8008"

      PATRONI_POSTGRESQL_LISTEN: "0.0.0.0:5432"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni3:5432"

      PATRONI_POSTGRESQL_DATA_DIR: "/home/postgres/pgdata/pgroot/data"

      PATRONI_SUPERUSER_USERNAME: "${SUPERUSER}"
      PATRONI_SUPERUSER_PASSWORD: "${SUPERPASS}"
      PATRONI_REPLICATION_USERNAME: "${REPLUSER}"
      PATRONI_REPLICATION_PASSWORD: "${REPLPASS}"

      PATRONI_POSTGRESQL_PARAMETERS_TIMEZONE: "${TIME_ZONE}"
      TZ: "${TIME_ZONE}"

      PATRONI_ETCD_HOSTS: "etcd:2379"
      PATRONI_DCS: |
        {"etcd3":{"hosts":["etcd:2379"]}, "loop_wait": 10, "ttl": 30, "retry_timeout": 10, "maximum_lag_on_failover": 1048576, "postgresql": {"use_pg_rewind": true}}
    volumes:
      - ./patroni_data/node3:/home/postgres/pgdata/pgroot/data
    depends_on:
      etcd:
        condition: service_healthy
    networks: [patroninet]

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    ports: ["${HAPROXY_PRIMARY_HOST_PORT}:5432", "${HAPROXY_REPLICA_HOST_PORT}:5433"]
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on: [patroni1, patroni2, patroni3]
    networks: [patroninet]

  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd
    ports: ["2379:2379"]
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=false
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379      
    networks: [patroninet]
    healthcheck:
      test: ["CMD", "etcdctl", "--endpoints=http://localhost:2379", "endpoint", "health"]
      interval: 5s
      timeout: 3s
      retries: 10


networks:
  patroninet:
    external: true