services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}        
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data  
  wait:
    image: postgres:15
    entrypoint: >
      sh -c '
        until pg_isready -h postgres_db -p 5432 -U ${POSTGRES_USER};
        do echo "Ожидание готовности постгреса..."; sleep 2; done;
      '
    depends_on:
      - postgres
  flyway:
    image: flyway/flyway:latest
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}    
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      MIGRATION_VERSION: ${MIGRATION_VERSION:-}
    entrypoint: >
      sh -c '
        if [ -n "$MIGRATION_VERSION" ]; then
          flyway migrate -X -target="$MIGRATION_VERSION";
        else 
          flyway migrate -X;
        fi
      '
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      wait:
        condition: service_completed_successfully
  seed:
    build: ./seed
    volumes: 
      - ./seed:/app
    environment:
      APP_ENV: ${APP_ENV}
      SEED_COUNT: ${SEED_COUNT}
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER} 
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      flyway:
        condition: service_completed_successfully
  