ALTER TABLE Trains
DROP COLUMN IF EXISTS total_carriages,
DROP COLUMN IF EXISTS total_seats,
ADD COLUMN IF NOT EXISTS name varchar(255);

ALTER TABLE Carriages
DROP COLUMN IF EXISTS capacity;

ALTER TABLE AgeCategories 
DROP COLUMN IF EXISTS price;